In [3]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

In [4]:
print(type(np_height))

<class 'numpy.ndarray'>


In [5]:
#calculate BMI
bmi = np_weight / np_height ** 2

print(bmi)


[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


In [7]:
# for a boolean response
bmi > 24

#print only those observations above 23
bmi[bmi > 24]

array([27.88755755, 28.75558507, 25.48723993, 25.84368152])

In [8]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

#making numpy arrays
np_weight_kg = np.array(weight_kg)

In [9]:
print(type(np_weight_kg))

<class 'numpy.ndarray'>


In [11]:
np_weight_lbs = 2.2 * np_weight_kg

print(np_weight)

[81.65 97.52 95.25 92.98 86.18 88.45]


In [12]:
dict = {"country": ["Brazil", "Russia", "India", "China", "South Africa"],
       "capital": ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "population": [200.4, 143.5, 1252, 1357, 52.98] }

import pandas as pd
brics = pd.DataFrame(dict)
print(brics)

country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Dehli   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98


In [13]:
# Set the index for brics
brics.index = ["BR", "RU", "IN", "CH", "SA"]

# Print out brics with new index values
print(brics)

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Dehli   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98


In [5]:
# Import pandas as pd
import pandas as pd

# Import the cars.csv data: cars
cars = pd.read_csv('cars.csv')

# Print out cars
print(cars)

Unnamed: 0  cars per cap        country  drives right
0         US           809  United States          True
1        AUS           731      Australia         False
2        JAP           588          Japan         False
3         IN            18          India         False
4         RU           200         Russia          True
5        MOR            70        Morocco          True
6         EG            45          Egypt          True


In [7]:
# Import pandas and cars.csv
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Print out country column as Pandas Series
print(cars['cars per cap'])

# Print out country column as Pandas DataFrame
print(cars[['cars per cap']])

# Print out DataFrame with country and drives_right columns
print(cars[['cars per cap', 'country', 'drives right']])

US     809
AUS    731
JAP    588
IN      18
RU     200
MOR     70
EG      45
Name: cars per cap, dtype: int64
     cars per cap
US            809
AUS           731
JAP           588
IN             18
RU            200
MOR            70
EG             45
     cars per cap        country  drives right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True


In [8]:
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Print out first 4 observations
print(cars[0:4])

# Print out fifth and sixth observation
print(cars[4:6])

cars per cap        country  drives right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
     cars per cap  country  drives right
RU            200   Russia          True
MOR            70  Morocco          True


In [9]:
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Print out observation for Japan
print(cars.iloc[2])

# Print out observations for Australia and Egypt
print(cars.loc[['AUS', 'EG']])

cars per cap      588
country         Japan
drives right    False
Name: JAP, dtype: object
     cars per cap    country  drives right
AUS           731  Australia         False
EG             45      Egypt          True
